name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and run tests
        working-directory: ./kafka-producer-consumer-example
        run: lein deps && lein test
      - name: Install dependencies and run tests
        working-directory: ./kafka-streams-example
        run: lein deps && lein test
